stages:
  - docker-build

variables:
  USER_NAME: "scor2k"
  IMAGE_NAME: "nxter-sigbro-wallet-web"
  VER: '3.8.0'

Build docker image:
  image: docker:latest
  stage: docker-build
  services:
    - docker:dind
  script:
    - mkdir -p ~/.docker && echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    - docker build --tag $USER_NAME/$IMAGE_NAME:$VER .
    - docker push $USER_NAME/$IMAGE_NAME:$VER
    - rm -f ~/.docker/config.json
  only:
    - master
  tags:
    - docker
